theme: jekyll-theme-cayman

name: C Comment Remover

title: C Comment Remover

avatar: https://avatars2.githubusercontent.com/u/43686459?s=400&v=4

footer-links: 
  email: github@bwuah.me
  github: lennihein
  twitter: bwuaaah
  stackoverflow: users/8114293/lennihein
